import { Movie } from '@/types/movie';

// Pre-seeded mock movies (will be used when localStorage is empty)
export const mockMovies: Movie[] = [
  {
    id: 'mock-1',
    title: 'Troy',
    genre: 'War',
    rating: 7,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7, // 7 days ago
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Troy_03500296.png',
  },
  {
    id: 'mock-2',
    title: 'The Covenant',
    genre: 'War',
    rating: 10,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3, // 3 days ago
    posterUrl:
      'https://m.media-amazon.com/images/M/MV5BMTA0MTgwYWUtMTA5Ni00NTA1LTk5ZmUtYzQxMDU4MTgwMmM1XkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-3',
    title: 'The Boy in the Striped Pajamas',
    genre: 'Drama',
    rating: 10,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
    posterUrl: 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p187089_p_v8_an.jpg',
  },
  {
    id: 'mock-4',
    title: 'Jungle',
    genre: 'Adventure',
    rating: 7,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
    posterUrl: 'https://static.toiimg.com/photo/61987264.cms',
  },
  {
    id: 'mock-5',
    title: 'Operation Mekong',
    genre: 'War',
    rating: 6,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 16,
    posterUrl: 'https://play-lh.googleusercontent.com/q9awHngLzT0oqNw0dYV97Wp7xEWT79GRSi7J68XZeDeSqwred8A9FD9JU8CYM64y9-bxRQ',
  },
  {
    id: 'mock-6',
    title: 'Ghosted',
    genre: 'Romance',
    rating: 3,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZDI0YzJjZTctNjU0MS00Y2Y3LThkNDgtNWMxYWVlZjVkYzYwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-7',
    title: 'Alpha',
    genre: 'Adventure',
    rating: 3,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzkzMzNmZTUtODU3ZS00MmNkLWI2MzMtYzExMWY4ZDNiZjBiXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-8',
    title: 'Death Race',
    genre: 'Action',
    rating: 6,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 13,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZjdlNmJjM2ItYjkwOS00NDMxLWFjM2QtNzcyZjJkYzEzYzQ5XkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-9',
    title: 'Enemy at the Gates',
    genre: 'War',
    rating: 9,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BODM5MmQyYjktMzg5Ny00Y2Y1LThlNWQtNjQ5OGMwNmY2YjcyXkEyXkFqcGc@._V1_QL75_UX190_CR0,1,190,281_.jpg',
  },
  {
    id: 'mock-10',
    title: 'Fall',
    genre: 'Adventure',
    rating: 6,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 11,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSF5bpuBcL40CYVZiqaqPOZIDoHWlLuIg9r-PN9WLphR7C_REEHxqsS5PJ64jerXnTOggol&s=10',
  },
  {
    id: 'mock-11',
    title: 'Waktu Magrib',
    genre: 'Horror',
    rating: 6,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BOTljNDg5M2QtOTQ1YS00N2QzLTlhOTgtNDg5MDcxMTNjYWZmXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-12',
    title: 'After Everything',
    genre: 'Romance',
    rating: 2,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3lKxzw2Y1V2Gltg7j-EGqpGZOGue8OPlz4jyEmm92eQdb_uMcqZ_Zw6HfQS0tgG_TAy1WJqoyveQYoigBuX3W1v4lvfMKlw1k-vZqSA&s=10',
  },
  {
    id: 'mock-13',
    title: 'Snowpiercer',
    genre: 'Sci-Fi',
    rating: 6,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTQ3NzA1MTY3MV5BMl5BanBnXkFtZTgwNzE2Mzg5MTE@._V1_.jpg',
  },
  {
    id: 'mock-14',
    title: 'Chor Nikal Ke Bhaga',
    genre: 'Thriller',
    rating: 9,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNTgwMmVlZjgtMDhjMC00ZGU2LTgyNGEtOGM1ZDQ0Y2VmZjdlXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-15',
    title: 'A Thursday',
    genre: 'Thriller',
    rating: 5,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPmy860Y4OkqdXfkqSq3wXd3bkVYwQKIgBHl-xh3BBoEcwWn8dS_rfYlT0ev5UxLMVYhvfhkz7TpCzCMzXVJTwVK5nv8iMTEFg0BieDw&s=10',
  },
  {
    id: 'mock-16',
    title: 'Nowhere',
    genre: 'Adventure',
    rating: 5,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZmQwODM5NTctYzRkMi00MmIwLWFjODAtMTFiMWY2OWE3MGQyXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-17',
    title: 'The Gangster, The Cop, The Devil',
    genre: 'Action',
    rating: 7,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS_SenUIck3Opt5qrfPa2mH-VFvhsmh8amnI9jFbt0CoFHbVJCtWoMhDPjUeIERCJSuriX8_1Jrdn2rHKE_TpztOKwUFoaCF4LvXQteQ&s=10',
  },
  {
    id: 'mock-18',
    title: 'Ittefaq',
    genre: 'Thriller',
    rating: 9,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f0/Ittefaq_%282017%29.jpg',
  },
  {
    id: 'mock-19',
    title: 'The Roundup',
    genre: 'Action',
    rating: 7,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi6Uuzmr_m4BrkektU6jwWvS1_GCQi6dOhLocnLo3dgtxVdajnBsKjS_BZgW54Ar__IiJe_rhu2LD7BFCi5nz-o96FAracy_MU8SXRtVw&s=10',
  },
  {
    id: 'mock-20',
    title: 'Section 375',
    genre: 'Thriller',
    rating: 8,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTqTT4SOgnFdt44Uwi9ePRD_LCv5vG5pcOtD4Mw0pdzPP6xc99K',
  },
  {
    id: 'mock-21',
    title: 'Escape from Alcatraz',
    genre: 'Thriller',
    rating: 7,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
    posterUrl: 'https://resizing.flixster.com/QC7tldHjjCFGfsQ5xU-BRPEZP_Y=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p3635_v_v9_aa.jpg',
  },
  {
    id: 'mock-22',
    title: 'Green Zone',
    genre: 'War',
    rating: 0,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 11,
    posterUrl: 'https://m.media-amazon.com/images/I/510T1i5-uTL._AC_UF894,1000_QL80_.jpg',
  },
  {
    id: 'mock-23',
    title: '12th Fail',
    genre: 'Drama',
    rating: 10,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 10,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5DkHD2DdxZsC6JwO2bWHD087VaJiANsYHDU7nr_JjRYwQzby5CdS6HkQqDHjmDw-U0r-4_g&s=10',
  },
  {
    id: 'mock-24',
    title: 'Operation Red Sea',
    genre: 'War',
    rating: 6,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 9,
    posterUrl: 'https://wellgousa.com/sites/default/files/2023-02/OperationRedSea-IntenseChineseActionWarAdventure-WellGoUSA-KeyArtPoster-812x1200.jpeg',
  },
  {
    id: 'mock-25',
    title: 'The Stoning of Soraya M.',
    genre: 'Drama',
    rating: 10,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
    posterUrl: 'https://m.media-amazon.com/images/I/71fvLa9KwlL._AC_UF894,1000_QL80_.jpg',
  },
  {
    id: 'mock-26',
    title: 'Perfume: The Story of a Murderer',
    genre: 'Thriller',
    rating: 4,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 7,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTg2Mzk2NjkzNl5BMl5BanBnXkFtZTYwMzIzOTc2._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-27',
    title: 'Ambulance',
    genre: 'Action',
    rating: 8,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 6,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUuTm5ncE6dYHAX5Plo_UfJLd9bLcFiui-Rm5O5qBAqtTuMOUI301fZmOOoSk-wL5uGUi0FQ&s=10',
  },
  {
    id: 'mock-28',
    title: "Wrath of Man",
    genre: 'Action',
    rating: 8,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BODE4ZGY4OTktNDBjMy00NGVkLTk5YWUtNjA3NGU3MTA5NzM0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-29',
    title: 'Mechanic: Resurrection',
    genre: 'Action',
    rating: 8,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 4,
    posterUrl: 'https://4.bp.blogspot.com/-xqWmtXxPPDk/WPpfXQqH9lI/AAAAAAAAAG8/nX0ATjcaag8QxW7GIs9k1wU2zdEIPDBgQCLcB/s1600/Mechanic-Resurrection-2016.jpg',
  },
  {
    id: 'mock-30',
    title: 'Blue Valentine',
    genre: 'Romance',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTU4MTQ2MzA1Ml5BMl5BanBnXkFtZTcwODE3NTgwNA@@._V1_.jpg',
  },
  {
    id: 'mock-31',
    title: 'Atonement',
    genre: 'Romance',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    posterUrl: 'https://images.mubicdn.net/images/artworks/814853/cache-814853-1752004860/images-original.png',
  },
  {
    id: 'mock-32',
    title: 'Revolutionary Road',
    genre: 'Romance',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTczNDgzMjczOV5BMl5BanBnXkFtZTcwOTU3MzMwMg@@._V1_.jpg',
  },
  {
    id: 'mock-33',
    title: '365 Days',
    genre: 'Romance',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTg5N2U4ZTItMjc2NC00NDg2LWIzODYtOWZmNzY5Yzc5MzUxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-34',
    title: 'The Handmaiden',
    genre: 'Romance',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
    posterUrl: 'https://media-cache.cinematerial.com/p/500x/e42hiyov/the-handmaiden-movie-poster.jpg?v=1535288517',
  },
  {
    id: 'mock-35',
    title: 'Chloe',
    genre: 'Romance',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    posterUrl: 'https://images.justwatch.com/poster/180134193/s718/chloe-2009.jpg',
  },
  {
    id: 'mock-36',
    title: 'The Godfather',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAY2xsJVIZxm3K0gNtOMr9CSCvLdr5kdo3V3pv2HMuUkTBhFzRe5-b8NDRmO1mt5S5Xp_YyQ&s=10',
  },
  {
    id: 'mock-37',
    title: "Schindler's List",
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZI1MgjT4Z5M5_sAsBw36VYXHPN0iqdr_XmwYGyEYoI7y-5sor40I2j6TfWIS7eHc70LkARRkURihENhecCgCMXNUovgE_pc7otKrH7Q&s=10',
  },
  {
    id: 'mock-38',
    title: 'Apocalypse Now',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpRP-MOLF1JzP8QDpvOGlrCVxtTfkflrakuA&s',
  },
  {
    id: 'mock-39',
    title: 'Taxi Driver',
    genre: 'Crime',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZDNhMGYwM2UtMTdlZS00MGQ1LWI2YzAtODY5YWI1MjYyNzRmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-40',
    title: 'Inception',
    genre: 'Sci-Fi',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg',
  },
  {
    id: 'mock-41',
    title: 'Parasite',
    genre: 'Thriller',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-42',
    title: 'Oldboy',
    genre: 'Action',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFSnng9RUnb3FXPa3L8aDi0ltE5wdFAHmjWA&s',
  },
  {
    id: 'mock-43',
    title: 'The Shawshank Redemption',
    genre: 'Crime',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
    posterUrl: 'https://images.jdmagicbox.com/comp/jd_social/news/2018jul21/image-119206-zkypi64x2m.jpg',
  },
  {
    id: 'mock-44',
    title: 'Gone Girl',
    genre: 'Thriller',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    posterUrl: 'https://akns-images.eonline.com/eol_images/Entire_Site/201408/rs_634x845-140108072345-634.Gone-Girl-Ben-Affleck-Rosamund-Pike.jl.010814.jpg?fit=around%7C634:845&output-quality=90&crop=634:845;center,top',
  },
  {
    id: 'mock-45',
    title: 'Saving Private Ryan',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 11,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEnRks_jW1cO8QE29uvpLvtkojAzFt6iNUoiNNNqt_nxL8iiUa_AQrGa7yU0rcy3vxMOPT0hCT-r8fF7dWSV-cUpsBTTOG35RbQTHgnA&s=10',
  },
  {
    id: 'mock-46',
    title: 'The Thin Red Line',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
    posterUrl: 'https://images.moviesanywhere.com/8dc93190a4e065d353a9950194399474/fb0b42cc-9793-43d8-bedf-042ac316ef65.jpg',
  },
  {
    id: 'mock-47',
    title: 'Come and See',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 13,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxnc3ulgdT3i4NIJ800NkJfFTb7v2bS6cW7A&s',
  },
  {
    id: 'mock-48',
    title: '1917',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStLVXEGRgSilajmqZ79UfkTy_hkDnKeod4k4u_7U-_-8wUlNBfjSVNx6cSH17gnQuDmYzqDQ&s=10',
  },
  {
    id: 'mock-49',
    title: 'Black Hawk Down',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
    posterUrl: 'https://www.revolutionstudios.com/wp-content/uploads/2015/09/black_hawk.jpg',
  },
  {
    id: 'mock-50',
    title: 'Dunkirk',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 16,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe99rkQPNs3ZkNLDnAwcq6r0UzesiT64NqSztuvHKUJUnsrcONbFX7qJg_crnLW7BBb3mkZg&s=10',
  },
  {
    id: 'mock-51',
    title: 'Hacksaw Ridge',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 17,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSogFPfZcNeyQCqhuKGazDuG3e2rrEeBYXzD7vrxG9nTOpLc61LvqDNTysiJEJOd7QFQwPv&s=10',
  },
  {
    id: 'mock-52',
    title: 'Lone Survivor',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
    posterUrl: 'https://th.bing.com/th/id/OIP.dXdVUOiv_uUJcfUksLDJoAHaK9?w=120&h=180&c=7&r=0&o=7&pid=1.7&rm=3',
  },

  {
  id: 'mock-53',
  title: 'Eko',
  genre: 'Adventure',
  rating: 0,
  watched: false, // watchlist
  createdAt: Date.now(),
  posterUrl: 'https://m.media-amazon.com/images/M/MV5BMWNjNDRjYTctYmMxMS00Y2MzLWI4YjUtYTBhNjRiMWMwMDkxXkEyXkFqcGc@._V1_.jpg',
},

{
  id: 'mock-54',
  title: '777 Charlie',
  genre: 'Adventure',
  rating: 5,
  watched: true,
  createdAt: Date.now(),
  posterUrl: 'https://m.media-amazon.com/images/M/MV5BOWY4MzlmNjItZGYzMS00ZDVhLWI2ZDMtNWEwZTBiMmU0YzQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
},


{
  id: 'mock-55',
  title: 'No Strings Attached',
  genre: 'Romance',
  rating: 5,
  watched: true,
  createdAt: Date.now(),
  posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMKnNXTiTrUZ61q_kwSxgwjCuYsVpnX_m9oCfmMBQbzciuEtvh1nYjkq_zce56IAyrbezBbg&s=10',
},

{
  id: 'mock-56',
  title: 'Anora',
  genre: 'Romance',
  rating: 0,
  watched: false, // watchlist
  createdAt: Date.now(),
  posterUrl: 'https://m.media-amazon.com/images/M/MV5BYThiN2M0NTItODRmNC00NDhlLWFiYTgtMWM2YTEyYzI3ZTY1XkEyXkFqcGc@._V1_.jpg',
},


{
  id: 'mock-57',
  title: 'Shutter Island',
  genre: 'Thriller',
  rating: 7,
  watched: true,
  createdAt: Date.now(),
  posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWaASGt5HkTiOySkGsHTkXv4l_SCqlgCdpiCMbai76YykQMsJNGbobjcea6jWH-wvqVE9XGw&s=10',
},





];

const key = 'movie-tracker-data';
localStorage.removeItem('movie-tracker-data');

export default mockMovies;
