import { Movie } from '@/types/movie';

// Pre-seeded mock movies (will be used when localStorage is empty)
export const mockMovies: Movie[] = [
  {
    id: 'mock-1',
    title: 'Troy',
    genre: 'War',
    rating: 7,
    watched: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7, // 7 days ago
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Troy_03500296.png',
  },
  {
    id: 'mock-2',
    title: 'The Covenant',
    genre: 'War',
    rating: 10,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3, // 3 days ago
    posterUrl:
      'https://m.media-amazon.com/images/M/MV5BMTA0MTgwYWUtMTA5Ni00NTA1LTk5ZmUtYzQxMDU4MTgwMmM1XkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-3',
    title: 'The Boy in the Striped Pajamas',
    genre: 'Drama',
    rating: 10,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
    posterUrl: 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p187089_p_v8_an.jpg',
  },
  {
    id: 'mock-4',
    title: 'Jungle',
    genre: 'Adventure',
    rating: 7,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
    posterUrl: 'https://static.toiimg.com/photo/61987264.cms',
  },
  {
    id: 'mock-5',
    title: 'Operation Mekong',
    genre: 'War',
    rating: 6,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 16,
    posterUrl: 'https://play-lh.googleusercontent.com/q9awHngLzT0oqNw0dYV97Wp7xEWT79GRSi7J68XZeDeSqwred8A9FD9JU8CYM64y9-bxRQ',
  },
  {
    id: 'mock-6',
    title: 'Ghosted',
    genre: 'Romance',
    rating: 3,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZDI0YzJjZTctNjU0MS00Y2Y3LThkNDgtNWMxYWVlZjVkYzYwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-7',
    title: 'Alpha',
    genre: 'Adventure',
    rating: 3,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzkzMzNmZTUtODU3ZS00MmNkLWI2MzMtYzExMWY4ZDNiZjBiXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-8',
    title: 'Death Race',
    genre: 'Action',
    rating: 6,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 13,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZjdlNmJjM2ItYjkwOS00NDMxLWFjM2QtNzcyZjJkYzEzYzQ5XkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-9',
    title: 'Enemy at the Gates',
    genre: 'War',
    rating: 9,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BODM5MmQyYjktMzg5Ny00Y2Y1LThlNWQtNjQ5OGMwNmY2YjcyXkEyXkFqcGc@._V1_QL75_UX190_CR0,1,190,281_.jpg',
  },
  {
    id: 'mock-10',
    title: 'Fall',
    genre: 'Adventure',
    rating: 6,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 11,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSF5bpuBcL40CYVZiqaqPOZIDoHWlLuIg9r-PN9WLphR7C_REEHxqsS5PJ64jerXnTOggol&s=10',
  },
  {
    id: 'mock-11',
    title: 'Waktu Magrib',
    genre: 'Horror',
    rating: 6,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BOTljNDg5M2QtOTQ1YS00N2QzLTlhOTgtNDg5MDcxMTNjYWZmXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-12',
    title: 'After Everything',
    genre: 'Romance',
    rating: 2,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3lKxzw2Y1V2Gltg7j-EGqpGZOGue8OPlz4jyEmm92eQdb_uMcqZ_Zw6HfQS0tgG_TAy1WJqoyveQYoigBuX3W1v4lvfMKlw1k-vZqSA&s=10',
  },
  {
    id: 'mock-13',
    title: 'Snowpiercer',
    genre: 'Sci-Fi',
    rating: 6,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTQ3NzA1MTY3MV5BMl5BanBnXkFtZTgwNzE2Mzg5MTE@._V1_.jpg',
  },
  {
    id: 'mock-14',
    title: 'Chor Nikal Ke Bhaga',
    genre: 'Thriller',
    rating: 9,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNTgwMmVlZjgtMDhjMC00ZGU2LTgyNGEtOGM1ZDQ0Y2VmZjdlXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-15',
    title: 'A Thursday',
    genre: 'Thriller',
    rating: 5,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPmy860Y4OkqdXfkqSq3wXd3bkVYwQKIgBHl-xh3BBoEcwWn8dS_rfYlT0ev5UxLMVYhvfhkz7TpCzCMzXVJTwVK5nv8iMTEFg0BieDw&s=10',
  },
  {
    id: 'mock-16',
    title: 'Nowhere',
    genre: 'Adventure',
    rating: 5,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZmQwODM5NTctYzRkMi00MmIwLWFjODAtMTFiMWY2OWE3MGQyXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'mock-17',
    title: 'The Gangster, The Cop, The Devil',
    genre: 'Action',
    rating: 7,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS_SenUIck3Opt5qrfPa2mH-VFvhsmh8amnI9jFbt0CoFHbVJCtWoMhDPjUeIERCJSuriX8_1Jrdn2rHKE_TpztOKwUFoaCF4LvXQteQ&s=10',
  },
  {
    id: 'mock-18',
    title: 'Ittefaq',
    genre: 'Thriller',
    rating: 9,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f0/Ittefaq_%282017%29.jpg',
  },
  {
    id: 'mock-19',
    title: 'The Roundup',
    genre: 'Action',
    rating: 7,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi6Uuzmr_m4BrkektU6jwWvS1_GCQi6dOhLocnLo3dgtxVdajnBsKjS_BZgW54Ar__IiJe_rhu2LD7BFCi5nz-o96FAracy_MU8SXRtVw&s=10',
  },
  {
    id: 'mock-20',
    title: 'Section 375',
    genre: 'Thriller',
    rating: 8,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTqTT4SOgnFdt44Uwi9ePRD_LCv5vG5pcOtD4Mw0pdzPP6xc99K',
  },
  {
    id: 'mock-21',
    title: 'Escape from Alcatraz',
    genre: 'Thriller',
    rating: 7,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
    posterUrl: 'https://resizing.flixster.com/QC7tldHjjCFGfsQ5xU-BRPEZP_Y=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p3635_v_v9_aa.jpg',
  },
  {
    id: 'mock-22',
    title: 'Green Zone',
    genre: 'War',
    rating: 0,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 11,
    posterUrl: 'https://m.media-amazon.com/images/I/510T1i5-uTL._AC_UF894,1000_QL80_.jpg',
  },
  {
    id: 'mock-23',
    title: '12th Fail',
    genre: 'Drama',
    rating: 10,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 10,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5DkHD2DdxZsC6JwO2bWHD087VaJiANsYHDU7nr_JjRYwQzby5CdS6HkQqDHjmDw-U0r-4_g&s=10',
  },
  {
    id: 'mock-24',
    title: 'Operation Red Sea',
    genre: 'War',
    rating: 6,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 9,
    posterUrl: 'https://wellgousa.com/sites/default/files/2023-02/OperationRedSea-IntenseChineseActionWarAdventure-WellGoUSA-KeyArtPoster-812x1200.jpeg',
  },
  {
    id: 'mock-25',
    title: 'The Stoning of Soraya M.',
    genre: 'Drama',
    rating: 10,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
    posterUrl: 'https://m.media-amazon.com/images/I/71fvLa9KwlL._AC_UF894,1000_QL80_.jpg',
  },
  {
    id: 'mock-26',
    title: 'Perfume: The Story of a Murderer',
    genre: 'Thriller',
    rating: 4,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 7,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTg2Mzk2NjkzNl5BMl5BanBnXkFtZTYwMzIzOTc2._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-27',
    title: 'Ambulance',
    genre: 'Action',
    rating: 8,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 6,
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUuTm5ncE6dYHAX5Plo_UfJLd9bLcFiui-Rm5O5qBAqtTuMOUI301fZmOOoSk-wL5uGUi0FQ&s=10',
  },
  {
    id: 'mock-28',
    title: "Wrath of Man",
    genre: 'Action',
    rating: 8,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BODE4ZGY4OTktNDBjMy00NGVkLTk5YWUtNjA3NGU3MTA5NzM0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  },
  {
    id: 'mock-29',
    title: "Mechanic: Resurrection",
    genre: 'Action',
    rating: 8,
    watched: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 4,
    posterUrl: 'https://4.bp.blogspot.com/-xqWmtXxPPDk/WPpfXQqH9lI/AAAAAAAAAG8/nX0ATjcaag8QxW7GIs9k1wU2zdEIPDBgQCLcB/s1600/Mechanic-Resurrection-2016.jpg',
  },
];

localStorage.setItem('movies', JSON.stringify(mockMovies));
const movies = JSON.parse(localStorage.getItem('movies') ?? '[]') as Movie[];

function nextId() {
  const key = 'movieIdCounter';
  const n = Number(localStorage.getItem(key) ?? 0) + 1;
  localStorage.setItem(key, String(n));
  return `movie-${n}`;
}

export default movies;
